export { default as Modal } from "./views/Modal";
export { default as Navbar } from "./views/Navbar";
export { default as Router } from "./views/Router";
export { default as Loader } from "./views/Loader";
export { default as InfoPage } from "./views/InfoPage";
export { default as ShopPage } from "./views/ShopPage";
export { default as AuthPage } from "./views/AuthPage";
export { default as AdminPanel } from "./views/AdminPage";
export { default as BasketPage } from "./views/BasketPage";
